
# Specify things which we want to train multitask netowrk on. Base netowrk perorms object Detection using FasterRCN
# valid types are regression, classification and segmetation and keypoints (all the image points can be specified in keypoints).
# Make sure the dataloder loads all the label names specified by names below

# Background and other classes
numclasses: 3
classes: ["color_board","cucumber"] 


segmentation:
    name: ["masks","backbone"]
    # Use all if the task is for all the classes
    classes: [["color_board","cucumber"],["cucumber"]]
    type: "segmentation"
    file: "/home/asad/projs/SMN/data/cucumber/labels_my-project-name_2021-12-17-03-00-40.json"
    

# Provide label name, class and number of classification you want to apply the classification
classification:
    name: ["neck","rating"]
    # For which class the classification is required
    classes: [["cucumber"],["cucumber"]]
    numclasses: [5,5]
    file: "/home/asad/projs/SMN/data/cucumber/labels_my-project-name_2021-12-17-03-00-26.csv"

regression:
    name: [None]
    # For which class the Regression is required
    class: [None]


keypoints:
    name: ["head","tail"] 
    classes: ["cucumber"]  
    num: 2
    file: "/home/asad/projs/SMN/data/cucumber/labels_my-project-name_2021-12-17-03-00-26.csv"
    
